# Projeto 2 - Ciência dos dados

## Eduardo Tirta
## Felipe Sigiani

In [30]:
%matplotlib inline

import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import pandas as pd
import numpy as np

import statsmodels.api as sm1 #Usa OLS com X como matriz de planejamento
import statsmodels.formula.api as sm  #Usa OLS como no R

print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\Felipe Lenda Sigiani\Documents\Estudos Felipe\2ºSemestre\Ciencia dos dados

In [31]:
dados = pd.read_excel('Indicator_Improved sanitation rural percent.xlsx',index_col=0)
dados1 = pd.read_excel("indicator_per capita total expenditure on health (ppp int. $).xlsx",index_col = 0)

In [32]:
dados.head()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,QUERO
"Proportion of the population using improved sanitation facilities, rural",,,,,,,,,,,,,,,,,,,,,
Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,28.0,...,28.0,28.0,29.0,29.0,29.0,29.0,30.0,30.0,30.0,30.0
Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,66.0,66.0,66.0,66.0,66.0,68.0,69.0,71.0,73.0,74.0,...,78.0,80.0,81.0,83.0,85.0,87.0,88.0,90.0,92.0,93.0
Algeria,77.0,77.0,77.0,77.0,78.0,78.0,79.0,80.0,81.0,81.0,...,83.0,84.0,85.0,85.0,86.0,87.0,88.0,88.0,88.0,88.0

In [33]:
dados=dados[~np.isnan(dados.QUERO)]

In [34]:
dados.head()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2001,2002,2003,2004,2005,2006,2007,2008,2009,QUERO
"Proportion of the population using improved sanitation facilities, rural",,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,27.0,27.0,27.0,27.0,27.0,27.0,27.0,27.0,28.0,...,28.0,28.0,29.0,29.0,29.0,29.0,30.0,30.0,30.0,30.0
Albania,66.0,66.0,66.0,66.0,66.0,68.0,69.0,71.0,73.0,74.0,...,78.0,80.0,81.0,83.0,85.0,87.0,88.0,90.0,92.0,93.0
Algeria,77.0,77.0,77.0,77.0,78.0,78.0,79.0,80.0,81.0,81.0,...,83.0,84.0,85.0,85.0,86.0,87.0,88.0,88.0,88.0,88.0
Andorra,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
Angola,6.0,6.0,6.0,6.0,6.0,7.0,8.0,9.0,9.0,10.0,...,12.0,13.0,14.0,14.0,15.0,16.0,17.0,18.0,19.0,19.0

In [35]:
d = pd.DataFrame()

In [36]:
d = dados.QUERO

In [37]:
d.head()

Proportion of the population using improved sanitation facilities, rural
Afghanistan     30.0
Albania         93.0
Algeria         88.0
Andorra        100.0
Angola          19.0
Name: QUERO, dtype: float64

In [38]:
d1 = pd.DataFrame()

In [39]:
dados1.head()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,Quero
Per capita total expenditure on health (PPP int. $),,,,,,,,,,,,,,,,
Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.114557,29.684998,32.124328,35.577605,36.167636,40.358763,38.255108,45.565772,44.465952
Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,105.870766,145.874213,156.120295,183.802111,225.253214,266.395628,279.082481,303.114667,326.034135,379.826416,406.901526,450.944023,493.882557,557.387321,591.483421,577.275816
Algeria,192.243807,180.373326,196.124726,206.136790,202.622356,188.073681,212.235307,225.208426,234.901186,227.205538,221.502879,232.780189,273.055581,299.398716,364.543940,330.006155

In [40]:
dados1=dados1[~np.isnan(dados1.Quero)]

In [42]:
d1 = dados1.Quero

In [43]:
d1.head()

Per capita total expenditure on health (PPP int. $)
Afghanistan      44.465952
Albania         577.275816
Algeria         330.006155
Andorra        3254.524918
Angola          168.130557
Name: Quero, dtype: float64